FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase
  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RT + A.on_pressed
    kp: [80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
    ts: [0, 1, 2]
    qs: [
      [],
      [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],
      [0.0, 0.9, -1.8, 0.0, 0.9, -1.8, 0.0, 0.9, -1.8, 0.0, 0.9, -1.8],
    ]
  Velocity:
    transitions: 
      Passive: LT + B.on_pressed
    policy_dir: config/policy/velocity
